### ISSUE TITLE
Periodic errors in resultant deformation fields

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/generate_deformation_fields#6]
I'm trying to create modified brains for a validation project.

I have created labels in two regions, and I am generated modified brains with volume changes in those segmented regions from 0.005 to 0.2 in steps. In all cases create_deformation.py produces deformation fields which have a periodic structure with "ringing" causing odd deformations within the brain.

An example invocation:
``tolerance.mnc`` is 1 outside the brain and 0 inside the brain
``20_percent_jac.mnc`` is 0.8 in one structure (small) and 1.2 in another structure (large) on contralateral sides.
```
> create_deformation.py -d /tmp -v -n 14 -t 0.0000001 -m tolerance.mnc \
      20_percent_jac.mnc transforms.xfm
```

Here, I attach a screenshot of the output jacobian and the input jacobian on the same scale:
![image](https://user-images.githubusercontent.com/3001850/59948068-09369a00-943d-11e9-8787-c3461296f394.png)

These ringinings in the deformation field are present even for the smallest input jacobian of 0.005

**Comment by bcdarwin** [comment]
Quite probably this is related to numpy changes, as with https://github.com/Mouse-Imaging-Centre/MICe-lab/issues/18 .

**Comment by bcdarwin** [comment]
Likely caused by https://github.com/Mouse-Imaging-Centre/pyminc/issues/37; please reopen if the issue persists with Pyminc 0.54.
